### ISSUE TITLE
Build route for querying number of commits 

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/git-technetium#4]
In order to return the number of commits per contributor in a repository, a route must be built on the server which queries the `https://developer.github.com/v3/repos/statistics/` endpoint.

**Comment by DrkSephy** [comment]
Completed by commit `b362797687cd4f812b229dbd0a083192337eb0f0`, `0cac24c4fb72239dba443ba80cd16000ed38786a`, and  `7dddb87137f515e9b5132ef5f0074321a462a304`.

**Comment by mk200789** [comment]
I will delete my comment.

**Comment by mk200789** [comment]
Test 2.
