### ISSUE TITLE
Pagination problems

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/git-technetium#57]
As we have recently discovered, the github API only returns a fixed amount of data at a time. The rest of any queried data can be retrieved by pagination. Therefore, we need a clean method of chaining several requests and checking if the needed data is not empty. If it is not empty on each page, we chain requests until we run into an empty set of data, i.e we are done parsing data.

**Comment by chessmasterhong** [comment]
See the links below for additional details on the API's paginated returned data and how to customize the results:
- [https://developer.github.com/v3/#pagination](https://developer.github.com/v3/#pagination)
- [https://developer.github.com/guides/traversing-with-pagination/](https://developer.github.com/guides/traversing-with-pagination/)

**Comment by DrkSephy** [comment]
Now that we know how to do a bunch of asynchronous requests using `async.js`, we need to address the pagination problems. See the following gist for a pseudo-algorithm which we would like to implement: `https://gist.github.com/DrkSephy/73e710af4ac0ce908603`.

The above is just my interpretation of it, but it captures the essence of the problem. Once this is done, we can finally begin to get all the data for any resource we like.

**Comment by DrkSephy** [comment]
As of commit `9ccf65ab10355b94656e6ca9dd3f24cc6a402ae6`, this problem has been solved. Major thanks to @ChocoShell  for helping to develop the algorithm for handling pagination. I will document and clean up the code soon.
