### ISSUE TITLE
Better report display

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/git-technetium#83]
Currently, the reports page looks like this: 
![report](https://cloud.githubusercontent.com/assets/1226900/3938622/fd4c6d6e-24bb-11e4-8dee-6f827975b64d.png)

If you view the source of `report.partial.html`, you will see how the layout is done. The reason for this is the format that the data comes back in, i.e: each request returns an object. It would be great if we could display all this data in a single chart, since the current layout is wasting whitespace. In order to do this, we need to grab all the data and format it such that it looks like this:

```
contributor: { name, commits, loc_added, loc_deleted, pull_requests, ... }
```

Which would allow us to iterate over each contributor and display the data as such:

```
<tr data-ng-repeat="contributor in pageData">
    <td> {{contributor.name}} </td>
    <td> {{contributor.commits}} </td>
    <td> {{ contributor.loc_added }} </td>
     ....
```

I haven't been successful with this yet. Any help is appreciated.

**Comment by DrkSephy** [comment]
Note: In case the `lines of code` and `commits` don't show up on the first query, this is because those come from the `contributors` endpoint, which takes some time to get the data and cache it. Usually if you request the data a second time, it will show up.

**Comment by DrkSephy** [comment]
I've been working on this for a while now, and so far I've come up with a way to package all the data into a nice form. However, when I try to render it on through the partial, nothing shows up. If you replace `reportController.js` with the code found: https://gist.github.com/DrkSephy/f75513b5b9c468ccd585 

I'm not sure why the data isn't accessible in the partial, even though I can clearly log it inside the controller. Below is a screenshot of the output in the debugger when console logging, you can see the format of the data:  

![screen shot 2014-08-16 at 12 13 45 am](https://cloud.githubusercontent.com/assets/1226900/3940905/cdc32bb0-24fb-11e4-83d4-5e214ff24559.png)

**Comment by chessmasterhong** [comment]
I'm getting an error saying that async is not defined in the reports controller. Line 23 in your gist.

**Comment by DrkSephy** [comment]
Oh yes, my apologies. To run this code, you'll need to grab a copy of `async.js`: https://github.com/caolan/async/tree/master/lib and place it within the `public/js` directory of our project, as well as update `public/index.html` to include the script. Everything should work then.

**Comment by chessmasterhong** [comment]
Upon looking through your code, here's the problem:

In `reportController.js`:

```
// ...
function (err, result) { // Line 151 in the gist
    //$scope.parsed = result;

    // Use this instead
    $scope.$apply(function() {
        $scope.parsed = result;
    });
});
```

Also, since `parsed` is the final dataset being used in the partial, use this instead for each table:

```
<tr data-ng-repeat="contributor in parsed">
```

There are a few tables that will missing data after doing this. You will need to fix the `<td>{{ contributor._____ }}</td>` in the table cells to reference the correct data in the `parsed` dataset -- specifically Issue Comments, Pull Requests, and Pull Request Comments.

**Comment by DrkSephy** [comment]
I will check that out. I know about the partial needing to be updated, but the $scope.$apply is new to me. Ironically, I was reading about that last night but it didn't click in my head that it would be useful. 

Thanks Kevin, I'll try it out.

**Comment by DrkSephy** [comment]
Your solution worked like a charm. Here is the new report layout: 
![new_report](https://cloud.githubusercontent.com/assets/1226900/3942521/98f459a4-2569-11e4-996e-ce38eb5a8cfd.png)

Pushing the changes soon.
