### ISSUE TITLE
Bug with reports module

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/git-technetium#86]
When querying a new repository, this error pops up occasionally: 

![errors](https://cloud.githubusercontent.com/assets/1226900/3942708/e5d56530-2571-11e4-8c09-e8362b9d63dc.png)

If you refresh the page and try to query a second time, it will work. This might be due to the nature of the asynchronous calls, but whenever it throws an error, it always seems to be with this line.

**Comment by DrkSephy** [comment]
I attempted to solve the problem with commit b57dfe0023c43ab5e715628c694ea417c56821a8,  but was not successful. 

I encourage testing other repositories to see what types of errors you come up with. If any new errors are found, open a new issue with a screenshot of it. 

Before we move forward with building new content on top of reports (i.e: graphs), this bug should be resolved first.

**Comment by chessmasterhong** [comment]
Off topic, but you are aware that just pasting the SHA-hash of the commit (without tick marks) will link to the commit. By adding the tick marks around the hash, it will convert to a monospaced format and break the link in the process. This makes it much more work than necessary to have to view the corresponding commit you were trying to reference. If in doubt, preview your markdown via the "Preview" tab just above the comment textbox before submitting it.
- https://help.github.com/articles/writing-on-github#references
- http://stackoverflow.com/a/8910323

**Comment by DrkSephy** [comment]
I actually was not aware of this. I will fix any previous issues that I do this in, and for the future as well. I edited my comment above yours to reflect this. Thanks for pointing that out.
