### ISSUE TITLE
Don't put libraries in repository, if possible.

### ISSUE THREAD

**Issue by chessmasterhong** [DrkSephy/git-technetium#88]
This issue raises a problem with the current method of handling dependencies and future maintenance of the project. As stated, don't put libraries in the project repository, if possible.
1. It makes it difficult to maintain library versions throughout the project. When a library gets revised and updated, we need to be able to track these changes. It is inefficient to have to go through each library, look at the version number, and compare with the latest version every couple of weeks or months. Then of course, the manual work of obtaining the latest version, copy/paste into the project, and sorting through compatibility issues.
2. It greatly skews a contributor's lines of code added (depending on if the library file(s) has been minified or not), making it seem like the contributor is writing a lot of custom code but in reality just added a couple of library files.

This is precisely the reason why Bower exists in our project -- to handle client-side libraries and address the aforementioned problems. In essence, if a library can be obtained from a repository, use Bower. Otherwise, use traditional copy/paste (such as code obtained through a generator, etc.) unless a more automated approach can be found.

All libraries currently existing in the project needs to be removed and integrated with Bower.

**Comment by DrkSephy** [comment]
Noted. There isn't a `bower install async` as far as I know, but either way it ends up skewing the lines of code. Will be avoided in the future.

**Comment by chessmasterhong** [comment]
http://bower.io/search/?q=async

**Comment by DrkSephy** [comment]
Gah. Sorry about that. I'll remove the library, install it via bower and update the dependencies.

**Comment by chessmasterhong** [comment]
I'm already working on it. I have Async installed via Bower already.
